// constants.js
// Constants used in Redux actions

module.exports = {
	SET_CONNECTION_STATUS: 'SET_CONNECTION_STATUS',
	SET_MUSE_INFO: 'SET_MUSE_INFO',
  SET_AVAILABLE_MUSES: 'SET_AVAILABLE_MUSES',
	SET_DESTINATION: 'SET_DESTINATION',
	UPDATE_PUB_SUB_CLIENT: 'UPDATE_PUB_SUB_CLIENT'
}
